### ISSUE TITLE
MyPal Landing page suggestion

### ISSUE THREAD

**Issue by wAndrewx** [X-TRON404/MyPal-dev#14]
Should we have a landing page to let users know what this platform is all about instead of leading straight to a login. I could do an initial page set up.

**Comment by X-TRON404** [comment]
> Should we have a landing page to let users know what this platform is all about instead of leading straight to a login. I could do an initial page set up.

Yes. Actually I have a sample landing page wireframe ready. I will share the design on discord. You can start working on that.

**Comment by wAndrewx** [comment]
Someone else can style and format the landing page, check out the discord for the layout
