### ISSUE TITLE
show when the comment/post/confession was posted with javascript-time-ago

### ISSUE THREAD

**Issue by X-TRON404** [X-TRON404/MyPal-dev#24]
<img width="694" alt="Screenshot 2021-10-05 at 4 48 07 PM" src="https://user-images.githubusercontent.com/55325140/136013211-63a73b0a-235e-4973-a463-b46f9fd8b147.png">

Here you can't see at what time the user posted the comment.
The goal here is to show when did the particular user post the particular comment.
You can use a JS library like *javascript-time-ago* to implement the same.

![WhatsApp Image 2021-10-05 at 11 46 48 PM](https://user-images.githubusercontent.com/55325140/136079975-ad089b1c-3c38-4ad3-b1a4-f3745a81154a.jpeg)

**Comment by mohamedamara1** [comment]
Hey can you assign me on this?

**Comment by X-TRON404** [comment]
@yahya-cloud Yes, it's right. Could you add this for comments and confessions too?

**Comment by yahya-cloud** [comment]
yes i have used the same approach and added time to all the comments and confession al
![Screenshot (308)](https://user-images.githubusercontent.com/59670962/137095127-8ac36489-801b-422e-881c-c22ce6a8862f.png)
s
![Screenshot (309)](https://user-images.githubusercontent.com/59670962/137095181-9e6fb426-4cd8-4772-800d-a0b3983d3338.png)
o
