### ISSUE TITLE
Improve the UI design for Comments section and search bar

### ISSUE THREAD

**Issue by supminn** [X-TRON404/MyPal-dev#3]
I would like to contribute to this project by adding a few styling improvements.

**Comment by X-TRON404** [comment]
> I would like to contribute to this project by adding a few styling improvements.
Now that you have changed the comments section for posts, it looks different from the comments section of confessions. Could you work on changing that too?

**Comment by X-TRON404** [comment]
hey, @supminn are you still working on improving the UI for the search bar?

**Comment by supminn** [comment]
Yes @X-TRON404, i will complete it by today and get this issue closed.
